services:

  api:
    image: eassbhhtgu/tplinkrelayapi:latest
    entrypoint: bash -c "/usr/sbin/update-ca-certificates && dotnet TPLinkRelayApi.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      HTTP_PORTS: "80"
    labels:
      traefik.http.routers.tplink-router.rule: Host(`tplink`)
      traefik.http.routers.tplink-router.tls: "true"
      traefik.http.services.tplink-service.loadbalancer.server.port: "80"
    secrets:
      - source: ca_crt
        target: /usr/local/share/ca-certificates/ca.crt

  traefik:
    image: traefik:latest
    command:
      - --api.insecure=true
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dynamic_conf/
    labels:
      traefik.http.routers.traefik-router.rule: Host(`traefik`)
      traefik.http.routers.traefik-router.tls: "true"
      traefik.http.services.traefik-service.loadbalancer.server.port: "8080"
    ports:
      - 443:443/tcp
    secrets:
      - source: localhost_crt
        target: /etc/certs/localhost.crt
      - source: localhost_key
        target: /etc/certs/localhost.key
    volumes:
      - ./traefik.yml:/etc/traefik/dynamic_conf/conf.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock

secrets:
  ca_crt:
    file: ${USERPROFILE}\.aspnet\https\ca.crt
  localhost_crt:
    file: ${USERPROFILE}\.aspnet\https\localhost.crt
  localhost_key:
    file: ${USERPROFILE}\.aspnet\https\localhost.key
