services:

  api:
    image: eassbhhtgu/tplinkrelayapi:latest
    entrypoint: bash -c "/usr/sbin/update-ca-certificates && dotnet TPLinkRelayApi.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      HTTP_PORTS: "80"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire:18889
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_SERVICE_NAME: tplink-relay-api
    labels:
      traefik.http.routers.tplink-router.rule: Host(`tplink`)
      traefik.http.routers.tplink-router.tls: "true"
      traefik.http.services.tplink-service.loadbalancer.server.port: "80"
    secrets:
      - source: ca_crt
        target: /usr/local/share/ca-certificates/ca.crt

  aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:18888
      DOTNET_DASHBOARD_OTLP_ENDPOINT_URL: http://0.0.0.0:18889
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "false"

      DASHBOARD__TELEMETRYLIMITS__MAXLOGCOUNT: "1000"
      DASHBOARD__TELEMETRYLIMITS__MAXMETRICSCOUNT: "1000"
      DASHBOARD__TELEMETRYLIMITS__MAXTRACECOUNT: "1000"

      DASHBOARD__OTLP__AUTHMODE: ApiKey
      DASHBOARD__OTLP__PRIMARYAPIKEY: c0b35c056105346aa1a89f3ce0bb8bf9c0c324182e40d4ec1a4e51a2a367a536
    labels:
      traefik.http.routers.aspire-router.rule: Host(`aspire`)
      traefik.http.routers.aspire-router.tls: "true"
      traefik.http.services.aspire-service.loadbalancer.server.port: "18888"

  traefik:
    image: traefik:latest
    command:
      - --api.insecure=true
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dynamic_conf/
    labels:
      traefik.http.routers.traefik-router.rule: Host(`traefik`)
      traefik.http.routers.traefik-router.tls: "true"
      traefik.http.services.traefik-service.loadbalancer.server.port: "8080"
    ports:
      - 443:443/tcp
    secrets:
      - source: localhost_crt
        target: /etc/certs/localhost.crt
      - source: localhost_key
        target: /etc/certs/localhost.key
    volumes:
      - ./traefik.yml:/etc/traefik/dynamic_conf/conf.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock

secrets:
  ca_crt:
    file: ${USERPROFILE}\.aspnet\https\ca.crt
  localhost_crt:
    file: ${USERPROFILE}\.aspnet\https\localhost.crt
  localhost_key:
    file: ${USERPROFILE}\.aspnet\https\localhost.key
